### ISSUE TITLE
reference genomes in samestr extract command

### ISSUE THREAD

**Issue by qinglong89** [danielpodlesny/samestr#11]
The module samestr extract obtains MetaPhlAn marker sequences from reference genomes by using BLASTN.
samestr extract \
--input-files reference_genomes/*.fasta \
--marker-dir marker_db/ \
--nprocs 30 \
--output-dir out_extract/

My question: where should we download the reference genomes? this is not clear to me.

Thanks!

**Comment by qinglong89** [comment]
NCBI refseq genomes?

ncbi-genome-download --section refseq --format fasta --parallel 80 bacteria

**Comment by danielpodlesny** [comment]
Yes, for example from NCBI or [proGenomes](https://progenomes.embl.de/download.cgi). `samestr extract` will extract the marker regions from the genome which can be compared and studied across genomes and metagenomes. Use `samestr convert` for dealing with metagenomes.

Hope this helps!
