### ISSUE TITLE
SameStr can only get one strain for a species from metaphlan database, right?

### ISSUE THREAD

**Issue by liangyong1991** [danielpodlesny/samestr#12]
I need to know "the strains number and name of a species", should I use other tools?

**Comment by danielpodlesny** [comment]
Hi, SameStr can compare and find both dominant and subdominant shared strains of a species between samples, so it is not restricted to just one strain. However, quantifying the number of strains is currently not possible - we're working on exactly such a feature. I'm not aware of any other tool that can do this at the moment, but feel free to link it if you find one.

**Comment by liangyong1991** [comment]
Thank you!
