### ISSUE TITLE
module extract 

### ISSUE THREAD

**Issue by tulikasriv26** [danielpodlesny/samestr#23]
please share the link from where I can download the reference genomes. I am truely struggling with it and in need to finish the analysis of my metagenomic samples in 10 days. I have tried progenomes and NCBI genomes (in short all) but they are not working. Please!!

**Comment by tulikasriv26** [comment]
Can your please comment and clarify? I will be highly obliged

**Comment by danielpodlesny** [comment]
Hi @tulikasriv26, I'm not sure what you are trying to achieve and what your steps have been so far. Both proGenomes and NCBI genomes can be used as input to SameStr and you can extract the relevant markers with `samestr extract` as described in the documentation. This is for genomes - but you're referring to a metagenomic analysis, so please provide a bit more context here

**Comment by tulikasriv26** [comment]
Thanks for your reply. I have metagenomic samples and want to perform strain tracking. I have completed samestr convert and received the output in .npz format for metagenomic files. Now, I need to perform samestr extraxt for reference genomes. Here, I am confused that form where I should download reference data? I have mixed bacterial and fungal strains identified. 
1. So, I am asking from where i should extract complete reference genome dataset? Because progenomes do not have reference fasta files for the genomes which i have obtained in my results in samestr convert. I am little bit confused here. 
2. Is thsi possible I can download the reference genomes from NCBI in fasta format only for those genomes which I get in samestr convert output files , so that they must be compared.

please reply, I will be highly obliged.

**Comment by danielpodlesny** [comment]
`samestr convert` converts alignment data into SNV-profile tables (the .npz files) for each clade, which you can then merge, filter, and compare between all sample pairs. This allows you to perform strain tracking based on the data generated from your samples alone.
Adding reference genomes would 'just' enable you to find those added reference strains if they were in your metagenomic sample. This could be useful if, for example, you knew a certain commercial probiotic was consumed, the sequence was publicly available, and you wanted to identify or track whether they could be found in the probands. If this is not the case, you could go on with your analysis using only your metagenomes.

**Comment by tulikasriv26** [comment]
Thank you so much for your detailed explaination. Honestly, it will be really helpful in my analysis. 
Yes, yo are correct. I have FMT data and I need to track some of the strains which we provide to the host as inoculum. In that case , we need reference strains? If yes, then do we need to download the reference sequences of those strains from NCBI? And then perform the samestr extract. Is that the correct sense?
I truely appreciate your help and explaination which you have provided earlier. Thanks. 
I am seeking for your response!

**Comment by danielpodlesny** [comment]
No, in this case, you don't need reference strains. You can proceed with convert > merge > filter > compare > summarize and then look for strain sharing between your respective donor and patient sampling.

**Comment by tulikasriv26** [comment]
Great, thanks for your response. 
Thanks
