### ISSUE TITLE
samestr filter 

### ISSUE THREAD

**Issue by tulikasriv26** [danielpodlesny/samestr#27]
I am performing filter module and receive this error 
![image](https://github.com/danielpodlesny/samestr/assets/35288788/6fdb0d5b-9e68-48e1-a95b-5313968004e8)

I have checked that concerned microbe is available in the database in sub-sub directories 
![image](https://github.com/danielpodlesny/samestr/assets/35288788/165800c3-f1a0-47e0-a4d3-328d4d1a6635)
Can you please help in this regard? The sub directories have weird names with _00,_01, _02 etc.

**Comment by tulikasriv26** [comment]
I am still struggling with the issue. I have updated the database and generated with sametsr_db, but nothing is working . I am receiving the similar error. Can you please help in rectifying this issue.

**Comment by tulikasriv26** [comment]
I have tried directly downloading from zenodo and utilize samestr db too.. but facing the same error. (screenshot attached above). Can you please help me in dealing with this issue. 
I will be highly obliged.

**Comment by tulikasriv26** [comment]
Can you please help me in rectifying this issue. One of my students have thesis submissions soon; we need to complete this issue fast. 
I will be highly obliged

**Comment by danielpodlesny** [comment]
Please provide more context: The taxonomic profiler you used, the database you downloaded, the commands you ran etc.

**Comment by tulikasriv26** [comment]
sure , First I have utilized samestr db module to generate the database
#!/bin/bash
#SBATCH --mem=300GB
#SBATCH --nodes=1
#SBATCH --partition=bigmem
#SBATCH --cpus-per-task 30
#SBATCH -J samestr_db
#SBATCH -o samestr_db.out
#SBATCH -e samestr_db.err
#SBATCH --time=24:00:00
#SBATCH --mail-user=*******************
#SBATCH --mail-type=ALL
samestr db --markers-info /work/ebg_lab/gm/wastewater_data/kraken2/db_MetaPhlAn/mpa_vJun23_CHOCOPhlAnSGB_202307.pkl --markers-fasta /work/ebg_lab/gm/wastewater_data/kraken2/db_MetaPhlAn/mpa_vJun23_CHOCOPhlAnSGB_202307.fna.bz2 --db-version /work/ebg_lab/gm/wastewater_data/kraken2/db_MetaPhlAn/mpa_latest --output-dir /work/ebg_lab/gm/wastewater_data/kraken2/samestr_db/

This works for me!. Then after performing merge module I have received the results in two format *.names.txt and *.npz format. Then I need to perform samestr filter module and utilize the stated batch file
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --mem=512GB
#SBATCH --partition=bigmem
#SBATCH --cpus-per-task 30
#SBATCH -J filter
#SBATCH -o filter.out
#SBATCH -e filter.err
#SBATCH --time=24:00:00
#SBATCH --mail-user=**************
#SBATCH --mail-type=ALL
samestr filter --input-files /work/ebg_lab/gm/wastewater_data/kraken2/out_merge/*.npz --input-names /work/ebg_lab/gm/wastewater_data/kraken2/out_merge/*.names.txt --marker-dir /work/ebg_lab/gm/wastewater_data/kraken2/samestr_db/ --samples-min-n-hcov 5000 --clade-min-samples 2 --marker-trunc-len 20 --global-pos-min-n-vcov 2 --sample-pos-min-n-vcov 5 --sample-var-min-f-vcov 0.1  --nprocs 30 --output-dir out_filter/

After running this ; I have received such errors 
![image](https://github.com/danielpodlesny/samestr/assets/35288788/0b5ce583-2efe-4973-a522-c9017edd4905)

Then, I tried downloading the databases from zenodo, but receiving the same error. 

Can you please help? In case you need more information please share your email; I will send the comoplete details of the data
I will be highly obliged

**Comment by danielpodlesny** [comment]
I'm a bit confused about the commands you used. Have you truncated `/work/ebg_lab/gm/wastewater_data/kraken2/out_merge/.npz` on purpose for this issue? Also, the convert step seems to be missing and the marker it is trying to fetch is not a valid marker for that Database or any other recent database. Could you confirm that you're running the latest samestr version with `samestr --version` which should be `samestr-1.2024.02-1`?

You can send me an [email](mailto:daniel.podlesny@embl.de) with more details.
