### ISSUE TITLE
Request to Add a Sample File to the Repository

### ISSUE THREAD

**Issue by yuzh321** [danielpodlesny/samestr#28]
Hi,

Could you please add a sample output file to the samestr repository? I'm trying to understand the output format from the summarize command, but I couldn't find any examples in the documentation or on GitHub. Having a sample file would be incredibly helpful for better understanding and utilizing this tool.

Thank you very much for your assistance!

**Comment by danielpodlesny** [comment]
Hi thanks for your suggestion! 

I added an example output for the `samestr stats` command that you would run after filtering the SNV profile https://github.com/danielpodlesny/samestr/commit/d3a8c364cec20ca31d0c3f196d40a3a93537e59d, as well as  three example output files from the `samestr summarize` command https://github.com/danielpodlesny/samestr/commit/7810b8d0b7db10171436442a6b040ac31dde078b that you should expect as a final output. You can find them at [samestr/example](https://github.com/danielpodlesny/samestr/tree/main/example)
