### ISSUE TITLE
Using samestr db with mpa_v30_CHOCOPhlAn_201901

### ISSUE THREAD

**Issue by danielpodlesny** [danielpodlesny/samestr#4]
Hi @danielpodlesny 

I have tried `samestr db` on metaphlan2, which works properly. 
However,  `samestr db` didnot work on metaphlan3. 
I followed the instruction on convert `mpa_v30_CHOCOPhlAn_201901.pkl` to `mpa_v30_CHOCOPhlAn_201901.py2.pkl ` using python3.7

When running `samestr db 
--mpa-pkl /db/metaphlan3/mpa_v30_CHOCOPhlAn_201901.py2.pkl 
--mpa-markers /db/metaphlan3/mpa_v30_CHOCOPhlAn_201901.fna 
--output-dir marker_db_metaphlan3/` 
I got the following warning messages:                                                                                                                                       
`Traceback (most recent call last):
  File "/ceph/home/yue.hu/.conda/envs/samestr/bin/samestr", line 1174, in <module>
    samestr(read_params())
  File "/ceph/home/yue.hu/.conda/envs/samestr/bin/samestr", line 924, in samestr
    mpa_pkl = pickle.load(bz2.BZ2File(input_args['mpa_pkl']))
EOFError`

_Originally posted by @huyue87 in https://github.com/danielpodlesny/samestr/issues/1#issuecomment-1148537157_

**Comment by danielpodlesny** [comment]
Hi @huyue87, 

Can you confirm that:
1. The pickle file at `/db/metaphlan3/mpa_v30_CHOCOPhlAn_201901.py2.pkl` is not empty? What is its size?
2. You deactivated the python3 environment that you used to convert the pickle file formats

**Comment by huyue87** [comment]
Hi @danielpodlesny ,

1. The size for `/db/metaphlan3/mpa_v30_CHOCOPhlAn_201901.py2.pkl` is 27M, and the original file is 25M.  

2. I didn't deactivate the python3 environment when converting the pickle file format. And I just deactivated py3 env as you suggested. The marker_db was successfully generated. 

Thanks for your prompt reply!

**Comment by danielpodlesny** [comment]
Glad this resolved your issue

**Comment by huyue87** [comment]
Hi @danielpodlesny ,

The profile.txt file exists and is not empty. It is a table with a four-line header as the metaphlan profile output showed on its tutorial.  

Inspired from your comment about specifying `--mp-profiles-dir` , I moved samestr working directory to the metaphlan output directory. And then, `samestr convert` running showed some improvement, that a `samopen` step was conducted (`[samopen] SAM header is present: 1131607 sequences.`). 
However, the convert run still showed error messages, please see below:

```
(samestr) [yue.hu@c1hitachi20 metaphlan]$  samestr convert \
--input-files testsample__2M_.sam.bz2 \
--marker-dir /db/metaphlan3/marker_db_metaphlan3/ \
--min-vcov 5 \
--nprocs 30 \
--output-dir samestr_out_convert/                                                                                                                                

2022-06-08 10:10:04,562 | DEBUG | __main__ | samestr | 875 | Number of input files: 1
2022-06-08 10:10:04,658 | DEBUG | samestr.convert._sam2bam | sam2bam | 23 | Converting: /ceph/projects/10.metaphlan3-test/output_dir/metaphlan/testsample__2M_.sam.bz2
[samopen] SAM header is present: 1131607 sequences.
ooSubprocess: dump_file.py --input_file /ceph/projects/10.metaphlan3-test/output_dir/metaphlan/testsample__2M_.sam.bz2 | filter_sam.py 90 40 | samtools view -bS - | samtools sort - -o testsample__2M_ > /ceph/projects/10.metaphlan3-test/output_dir/metaphlan/samestr_out_convert/bam/testsample__2M_.bam
2022-06-08 10:11:44,563 | DEBUG | samestr.convert._sam2bam | sam2bam | 56 | Finished: /ceph/projects/10.metaphlan3-test/output_dir/metaphlan/samestr_out_convert/bam/testsample__2M_.bam
2022-06-08 10:11:44,703 | DEBUG | samestr.convert._concatenate_gene_files | concatenate_gene_files | 18 | Gathering: /ceph/projects/10.metaphlan3-test/output_dir/metaphlan/testsample__2M_.profile.txt
Traceback (most recent call last):
  File "/ceph/home/yue.hu/.conda/envs/samestr/bin/samestr", line 1174, in <module>
    samestr(read_params())
  File "/ceph/home/yue.hu/.conda/envs/samestr/bin/samestr", line 918, in samestr
    input_args['nprocs'])
  File "/ceph/home/yue.hu/.conda/envs/samestr/lib/python2.7/site-packages/samestr/utils/ooSubprocess.py", line 252, in parallelize_async                                               
    results = [r.get() for r in app_results]
  File "/ceph/home/yue.hu/.conda/envs/samestr/lib/python2.7/multiprocessing/pool.py", line 572, in get                                                                                 
    raise self._value
IndexError: list index out of range
```

**Comment by danielpodlesny** [comment]
Hi @huyue87,

Have you followed the instructions in the [issue](https://github.com/danielpodlesny/samestr/issues/1#issuecomment-1097716999) you originally posted to? "four-line header" seems like you might not have run MetaPhlAn with its `--legacy-output` option. If that is the case it would be fastest if could quickly re-run MetaPhlAn from the `.bowtie2.bz2` file.

I have added the clarification from the [issue](https://github.com/danielpodlesny/samestr/issues/1#issuecomment-1097716999) to the readme.

**Comment by huyue87** [comment]
Hi @danielpodlesny ,
The samestr convert function works now! So I re-run Metaphlan and required "--legacy-output" as you suggested. 
Thanks for your advice.

**Comment by danielpodlesny** [comment]
Glad this resolved your issues! If that happens again in the future you might also want to use something along these lines to get back to the legacy metaphlan format:
`cat <(grep '^#SampleID' ${sample}.profile.txt) <(grep -v '^#' ${sample}.profile.txt | cut -f1,3) > ${sample}.profile_legacy.txt`
