### ISSUE TITLE
times for updates

### ISSUE THREAD

**Issue by nick-youngblut** [danielpodlesny/samestr#5]
SameStr looks very promising! I was wondering if you could provide timelines for the following:

* updating SameStr for mpa_vJan21_CHOCOPhlAnSGB_202103 (Metaphlan4) 
* updating to python 3
* publishing the package on pypi (and bioconda)

Also, it appears that you have a typo in the install instructions:

```
git clone https://github.com/danielpodlesny/samestr.git
cd samestr
conda env create           # <--- environment.yml not included
conda activate samestr
pip install .
```

**Comment by danielpodlesny** [comment]
Thanks for your interest in SameStr!

SameStr can already be used with the MetaPhlAn4 database. It requires a single workaround during database creation (see [here](https://github.com/danielpodlesny/samestr#compatibility-with-metaphlan-3)) that is related to the pending update to python 3. This isn't ideal - but it works. 

The update to python 3, along with the release to package managers, will hopefully come by the end of the year, but probably not before October. 

Thanks for your comment on the installation instructions. By default, `conda env create` looks for a `environment.yml` file in the current directory (hence `cd samestr/`).  Still, it's definitely more explicit to declare it in the command and I've updated the documentation on that.

**Comment by nick-youngblut** [comment]
>SameStr can already be used with the MetaPhlAn4 database

That's great!

>The update to python 3, along with the release to package managers, will hopefully come by the end of the year, but probably not before October.

Sounds good. Do you accept PRs in regards to the py2 => py3 update? 

>By default, conda env create looks for a environment.yml file in the current directory

I learned something new today. Thanks!

**Comment by nick-youngblut** [comment]
> The update to python 3, along with the release to package managers, will hopefully come by the end of the year, but probably not before October.

I'm circling back to considering `samestr` for some future work. Any updates on the python 3 update, adding samestr to bioconda, etc?

**Comment by danielpodlesny** [comment]
Thanks for your patience! I'll push something until eom.

**Comment by danielpodlesny** [comment]
python3 is done ([see release](https://github.com/danielpodlesny/samestr/releases/tag/v1.2023.02-1). pypi and bioconda will follow in the coming days

**Comment by danielpodlesny** [comment]
[7653e8e](https://github.com/danielpodlesny/samestr/commit/7653e8e253cbe76caf92ea855b67a8fe7840622e) closes this. I will be developing new features in the future. If there is anything you'd be interested in please reach out.
