### ISSUE TITLE
How SameStr works?

### ISSUE THREAD

**Issue by 123chenshixin** [danielpodlesny/samestr#6]
I have been read your publication and your work. However, I want to know why SameStr extracts MetaPhlAn2 marker sequences from reference genomes. It seems that it is not necessary for user to extract marker regions for detection of shared strains in metagenomic samples. I'm a novice in this field. I sincerely hope to get your patient reply.

**Comment by danielpodlesny** [comment]
Hi @123chenshixin,

You are correct: the `samestr extract` command has been added to additionally enable strain comparisons with sequences from isolate- or metagenome assembled genomes. `samestr extract` is not necessary for detecting shared strains between metagenomic samples - for this, you would follow the recommendations in the docs and use (at least) the following commands in that order:

1. [samestr convert](https://github.com/danielpodlesny/samestr#samestr-convert)
2. [samestr merge](https://github.com/danielpodlesny/samestr#merge)
3. [samestr filter](https://github.com/danielpodlesny/samestr#filter)
4. [samestr compare](https://github.com/danielpodlesny/samestr#compare)
5. [samestr summarize](https://github.com/danielpodlesny/samestr#summarize)

Make sure to set up your marker database with [samestr db](https://github.com/danielpodlesny/samestr#samestr-db) beforehand, and follow the instructions for [compatibility with metaphlan 3 and 4](https://github.com/danielpodlesny/samestr#compatibility-with-metaphlan-3).

**Comment by 123chenshixin** [comment]
Thank you for your helpful reply!
