### ISSUE TITLE
Do you have the command for reference genomes

### ISSUE THREAD

**Issue by StickHu** [danielpodlesny/samestr#9]
I am working on the project and stuck on the samestr extract. Can you tell me the command line for generating reference genomes? Thanks

**Comment by danielpodlesny** [comment]
Hi @StickHu ,

I'm not sure what you mean with "generating reference genomes". You can find the command for SameStr extract [here](https://github.com/danielpodlesny/samestr#extract). This will extract the marker regions from existing reference genomes if that is what you're trying to achieve.
